name: az_banking_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.1+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  loader_overlay: ^4.0.3
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.1.0
  flutter_svg: ^2.0.13
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  sentry: ^8.9.0
  timeago: ^3.7.0
  jwt_decoder: ^2.0.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  device_info_plus: ^11.3.0
  crypto: ^3.0.6
  google_maps_flutter: ^2.10.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  share_plus: ^7.2.1
  flutter_carousel_widget: ^3.1.0
  animated_bottom_navigation_bar: ^1.4.0
  flutter_widget_from_html: ^0.16.0
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  qr_code_scanner:
    git:
      url: https://github.com/wizmea/qr_code_scanner.git
  package_info_plus: ^8.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/transfer/
    - assets/icons/bills/
    - assets/icons/orders/
    - assets/icons/others/
    - assets/icons/cards/
    - assets/icons/settings/
